# Site settings
title: Peter John's Website
email: pjohn7@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal Portfolio and Blog of Peter John.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: peter765
github_username:  pjohn7

# Build settings
markdown: kramdown
